from __future__ import annotations

from pathlib import Path
from typing import Any

import gymnasium as gym
import numpy as np


NODE_POSITION_INDICES = np.asarray([0, 1, 2, 15, 16, 17, 30, 31, 32], dtype=np.int64)


class AnchorResidualTrackingEnv(gym.Wrapper):
    """Apply a learned residual around a replayable absolute-action reference.

    The wrapped environment is the real ManiSoft simulator.  ``reference.npz``
    contains ``target_positions[T+1,3,3]`` and ``u_ff[T,18]`` generated by the
    anchor script.  PPO emits a bounded residual; the wrapper applies
    ``clip(u_ff[t] + residual_limit * action)``.  The reward is purely geometric
    three-node tracking and contains no action or delta-action penalty.
    """

    def __init__(self, env: gym.Env, reference: str | Path, *, residual_limit: float = 0.02,
                 node_weights: tuple[float, float, float] = (1.0, 1.0, 2.0),
                 node_scales: tuple[float, float, float] = (0.005, 0.0075, 0.01),
                 metric_start_step: int = 100,
                 feedforward_scale: float = 1.0) -> None:
        super().__init__(env)
        path = Path(reference).expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(path)
        with np.load(path, allow_pickle=False) as archive:
            self.target_positions = np.asarray(archive["target_positions"], dtype=np.float32)
            self.u_ff = np.asarray(archive["u_ff"], dtype=np.float32)
        if self.target_positions.ndim != 3 or self.target_positions.shape[1:] != (3, 3):
            raise ValueError("target_positions must have shape [T+1,3,3]")
        if self.u_ff.shape != (self.target_positions.shape[0] - 1, 18):
            raise ValueError("u_ff must have shape [T,18]")
        self.residual_limit = float(residual_limit)
        self.feedforward_scale = float(feedforward_scale)
        self.node_weights = np.asarray(node_weights, dtype=np.float32)
        self.node_scales = np.asarray(node_scales, dtype=np.float32)
        if self.node_weights.shape != (3,) or self.node_scales.shape != (3,):
            raise ValueError("node weights/scales must have three entries")
        if (np.any(self.node_weights <= 0) or np.any(self.node_scales <= 0)
                or self.residual_limit <= 0 or not np.isfinite(self.feedforward_scale)
                or self.feedforward_scale <= 0):
            raise ValueError("node weights, scales and residual_limit must be positive")
        self.episode_steps = int(self.u_ff.shape[0])
        self.metric_start_step = int(metric_start_step)
        if not 0 <= self.metric_start_step < self.episode_steps:
            raise ValueError("metric_start_step must lie inside the episode")
        self.action_space = gym.spaces.Box(-1.0, 1.0, shape=(18,), dtype=np.float32)
        # physical state + 3-node XYZ target + target velocity + previous u + current u_ff
        self.observation_space = gym.spaces.Box(-np.inf, np.inf, shape=(99,), dtype=np.float32)
        self.step_count = 0
        self.previous_action = np.zeros(18, dtype=np.float32)
        self.errors: list[float] = []

    def _observation(self, state: np.ndarray, index: int) -> np.ndarray:
        index = int(np.clip(index, 0, self.episode_steps))
        target = self.target_positions[index].reshape(-1)
        if index < self.episode_steps:
            velocity = self.target_positions[index + 1] - self.target_positions[index]
            feedforward = self.feedforward_scale * self.u_ff[index]
        else:
            velocity = self.target_positions[index] - self.target_positions[index - 1]
            feedforward = self.feedforward_scale * self.u_ff[-1]
        return np.concatenate((state, target, velocity.reshape(-1), self.previous_action, feedforward)).astype(np.float32)

    def reset(self, **kwargs: Any):
        state, info = self.env.reset(**kwargs)
        state = np.asarray(state, dtype=np.float32).reshape(-1)
        if state.shape != (45,):
            raise ValueError("AnchorResidualTrackingEnv expects a 45-D physical state")
        self.step_count = 0
        self.previous_action.fill(0.0)
        self.errors = []
        return self._observation(state, 0), dict(info)

    def step(self, action: np.ndarray):
        action = np.asarray(action, dtype=np.float32).reshape(-1)
        if action.shape != (18,) or not np.isfinite(action).all():
            raise ValueError("residual action must be finite with shape (18,)")
        action = np.clip(action, -1.0, 1.0)
        feedforward = self.feedforward_scale * self.u_ff[self.step_count]
        requested = feedforward + self.residual_limit * action
        low = np.asarray(self.env.action_space.low, dtype=np.float32)
        high = np.asarray(self.env.action_space.high, dtype=np.float32)
        applied = np.clip(requested, low, high).astype(np.float32)
        state, _, terminated, truncated, info = self.env.step(applied)
        state = np.asarray(state, dtype=np.float32)
        self.step_count += 1
        actual = state[NODE_POSITION_INDICES].reshape(3, 3)
        target = self.target_positions[self.step_count]
        error = np.linalg.norm(actual - target, axis=1)
        normalized = error / self.node_scales
        reward = float(np.exp(-np.sum(self.node_weights * normalized**2) / np.sum(self.node_weights)))
        self.errors.append(float(error[2]))
        if self.step_count >= self.episode_steps:
            truncated = True
            circle_errors = np.asarray(self.errors[self.metric_start_step:], dtype=np.float64)
            info = dict(info)
            info.update({
                "circle_tracking_rmse": float(np.sqrt(np.mean(circle_errors**2))),
                "circle_tracking_p95": float(np.quantile(circle_errors, 0.95)),
                "mean_node_error": error.tolist(),
            })
        info = dict(info)
        info.update({
            "applied_action": applied.copy(),
            "feedforward_action": feedforward.copy(),
            "residual_action": (applied - feedforward).copy(),
            "node_error": error.copy(),
            "target_positions": target.copy(),
        })
        return self._observation(state, self.step_count), reward, terminated, truncated, info
